# Generated by Django 2.2.7 on 2021-02-23 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('bv_id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.IntegerField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
