# Generated by Django 2.2.7 on 2021-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210223_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='ip',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
