# Generated by Django 2.2.7 on 2021-02-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
