# Generated by Django 2.2.7 on 2021-03-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_likes_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
