# Generated by Django 2.2.7 on 2021-03-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userdetail_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bloger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserDetail'),
        ),
    ]
